//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roguelike.Core.Properties.i18n {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Roguelike.Core.Properties.i18n.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A boss arrives.
        /// </summary>
        public static string ABossArrives {
            get {
                return ResourceManager.GetString("ABossArrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Acolyte Flesh Devourer.
        /// </summary>
        public static string Acolyte {
            get {
                return ResourceManager.GetString("Acolyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alpha Wolf.
        /// </summary>
        public static string AlphaWolf {
            get {
                return ResourceManager.GetString("AlphaWolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are already full life.
        /// </summary>
        public static string AlreadyFullHealth {
            get {
                return ResourceManager.GetString("AlreadyFullHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à and.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à and takes {0} thorns damage.
        /// </summary>
        public static string AndTakeThornsDamage {
            get {
                return ResourceManager.GetString("AndTakeThornsDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A new day dawns.
        /// </summary>
        public static string ANewDayDawns {
            get {
                return ResourceManager.GetString("ANewDayDawns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A new traveler comes to the base camp !.
        /// </summary>
        public static string ANewTravelerComesToTheBaseCamp {
            get {
                return ResourceManager.GetString("ANewTravelerComesToTheBaseCamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arbalest bolt of the King&apos;s Valley.
        /// </summary>
        public static string ArbalestBoltOfTheKingsValley {
            get {
                return ResourceManager.GetString("ArbalestBoltOfTheKingsValley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reduce outlaws armor by {0}%.
        /// </summary>
        public static string ArbalestBoltOfTheKingsValleyDescription {
            get {
                return ResourceManager.GetString("ArbalestBoltOfTheKingsValleyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you serious? When I just explained it to you? Are you half-listening? Are you one of those people who taps their finger to move faster in conversations? You know what? Go ahead if you&apos;re so smart, the night is waiting for you....
        /// </summary>
        public static string ArminAreYouSerious {
            get {
                return ResourceManager.GetString("ArminAreYouSerious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Greetings, traveler. Welcome to Oneheim… or what remains of it. This village is but a heap of ruins. I have raised a camp here and set palisades against the night. Beware, for beyond these walls danger waits at every step..
        /// </summary>
        public static string ArminFirstMeeting {
            get {
                return ResourceManager.GetString("ArminFirstMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I can patch you up for {0} gold. You will recover up to +{1} HP..
        /// </summary>
        public static string ArminHealPitch {
            get {
                return ResourceManager.GetString("ArminHealPitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I can heal you. Come again when you will be damaged..
        /// </summary>
        public static string ArminHealPitchPlayerFullLife {
            get {
                return ResourceManager.GetString("ArminHealPitchPlayerFullLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back again? The wilds look harsh today. Tell me, friend, what may I do for you?.
        /// </summary>
        public static string ArminMeeting {
            get {
                return ResourceManager.GetString("ArminMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To arms! The shadows breach our palisades! Hold fast! We shall not yield!.
        /// </summary>
        public static string ArminMeetingBaseCampUnderAttack {
            get {
                return ResourceManager.GetString("ArminMeetingBaseCampUnderAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I heard ghastly cries beyond the walls, freezing the blood in my veins. Some foul creature prowls in the shadows. Beware, traveler..
        /// </summary>
        public static string ArminMeetingFirstBossComing {
            get {
                return ResourceManager.GetString("ArminMeetingFirstBossComing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Word has spread, you have vanquished that dreadful beast. Never had I imagined such strength in you. It is a true blessing to have you among us! Accept my eternal gratitude. Tell me, how might I repay such a debt?.
        /// </summary>
        public static string ArminMeetingFirstBossDefeated {
            get {
                return ResourceManager.GetString("ArminMeetingFirstBossDefeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travelers speak of a mighty foe haunting these lands. If only a valiant soul were strong enough to deliver us from this bane… May the camp’s palisades hold until then..
        /// </summary>
        public static string ArminMeetingFirstBossHere {
            get {
                return ResourceManager.GetString("ArminMeetingFirstBossHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à By the gods, you look on the brink of collapse! Rest a while. This camp was meant as a haven for the weary..
        /// </summary>
        public static string ArminMeetingPlayerLowLife {
            get {
                return ResourceManager.GetString("ArminMeetingPlayerLowLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à That is a heavy purse you carry. May it serve to raise Oneheim anew and kindle fresh hopes..
        /// </summary>
        public static string ArminMeetingPlayerRich {
            get {
                return ResourceManager.GetString("ArminMeetingPlayerRich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oneheim was a small village in the northeast of the old kingdom. There was a [red]disaster[/] and the village was [red]destroyed[/]..
        /// </summary>
        public static string ArminOneheimWasASmallVillage {
            get {
                return ResourceManager.GetString("ArminOneheimWasASmallVillage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I can repair the camp for {0} gold (+{1} HP)..
        /// </summary>
        public static string ArminRepairPitch {
            get {
                return ResourceManager.GetString("ArminRepairPitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Armor.
        /// </summary>
        public static string Armor {
            get {
                return ResourceManager.GetString("Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Armored Zombie.
        /// </summary>
        public static string ArmoredZombie {
            get {
                return ResourceManager.GetString("ArmoredZombie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assassin.
        /// </summary>
        public static string Assassin {
            get {
                return ResourceManager.GetString("Assassin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Base Camp.
        /// </summary>
        public static string BaseCamp {
            get {
                return ResourceManager.GetString("BaseCamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Base Camp HP: .
        /// </summary>
        public static string BaseCampHp {
            get {
                return ResourceManager.GetString("BaseCampHp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Be carefull, you are not safe here ....
        /// </summary>
        public static string BeCarefullYouAreNotSafeHere {
            get {
                return ResourceManager.GetString("BeCarefullYouAreNotSafeHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Berserker Necklace.
        /// </summary>
        public static string BerserkerNecklace {
            get {
                return ResourceManager.GetString("BerserkerNecklace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à +{0}% critical damage.
        /// </summary>
        public static string BerserkerNecklaceDescription {
            get {
                return ResourceManager.GetString("BerserkerNecklaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blade Of Heroes.
        /// </summary>
        public static string BladeOfHeroes {
            get {
                return ResourceManager.GetString("BladeOfHeroes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à +{0}% strengh against bosses.
        /// </summary>
        public static string BladeOfHeroesDescription {
            get {
                return ResourceManager.GetString("BladeOfHeroesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Boots of Echo Step.
        /// </summary>
        public static string BootsOfEchoStep {
            get {
                return ResourceManager.GetString("BootsOfEchoStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dodge increased by {0}% if your faster than you opponent.
        /// </summary>
        public static string BootsOfEchoStepDescription {
            get {
                return ResourceManager.GetString("BootsOfEchoStepDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Brigand of the Pierced Stone.
        /// </summary>
        public static string Brigand {
            get {
                return ResourceManager.GetString("Brigand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Butcher&apos;s Thorn Chaplet.
        /// </summary>
        public static string ButchersThornChaplet {
            get {
                return ResourceManager.GetString("ButchersThornChaplet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reduce cultist strengh by {0}%.
        /// </summary>
        public static string ButchersThornChapletDescription {
            get {
                return ResourceManager.GetString("ButchersThornChapletDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The camp is already in perfect shape..
        /// </summary>
        public static string CampAlreadyRepair {
            get {
                return ResourceManager.GetString("CampAlreadyRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can you heal me?.
        /// </summary>
        public static string CanYouHealMe {
            get {
                return ResourceManager.GetString("CanYouHealMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can you repair the camp?.
        /// </summary>
        public static string CanYouRepairTheCamp {
            get {
                return ResourceManager.GetString("CanYouRepairTheCamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cape Of Invisibility.
        /// </summary>
        public static string CapeOfInvisibility {
            get {
                return ResourceManager.GetString("CapeOfInvisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decrease by {0} enemies vision range.
        /// </summary>
        public static string CapeOfInvisibilityDescription {
            get {
                return ResourceManager.GetString("CapeOfInvisibilityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cave Troll.
        /// </summary>
        public static string CaveTroll {
            get {
                return ResourceManager.GetString("CaveTroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Champion Hand of Flesh.
        /// </summary>
        public static string Champion {
            get {
                return ResourceManager.GetString("Champion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chief of the Pierced Stone bandits.
        /// </summary>
        public static string ChiefBrigand {
            get {
                return ResourceManager.GetString("ChiefBrigand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choices.
        /// </summary>
        public static string Choices {
            get {
                return ResourceManager.GetString("Choices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Combat occurred!.
        /// </summary>
        public static string CombatOccurred {
            get {
                return ResourceManager.GetString("CombatOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cultist of the fresh meat.
        /// </summary>
        public static string Cultist {
            get {
                return ResourceManager.GetString("Cultist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dagger of life steal.
        /// </summary>
        public static string DaggerOfLifeSteal {
            get {
                return ResourceManager.GetString("DaggerOfLifeSteal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 60% chances to steal up to {0} life points from the enemy on hit..
        /// </summary>
        public static string DaggerOfLifeStealDescription {
            get {
                return ResourceManager.GetString("DaggerOfLifeStealDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dropped.
        /// </summary>
        public static string Dropped {
            get {
                return ResourceManager.GetString("Dropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drunkard.
        /// </summary>
        public static string Drunkard {
            get {
                return ResourceManager.GetString("Drunkard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enchanted Pouch.
        /// </summary>
        public static string EnchantedPouch {
            get {
                return ResourceManager.GetString("EnchantedPouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à +{0}% more gold after each victory.
        /// </summary>
        public static string EnchantedPouchDescription {
            get {
                return ResourceManager.GetString("EnchantedPouchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enemy defeated!.
        /// </summary>
        public static string EnemyDefeated {
            get {
                return ResourceManager.GetString("EnemyDefeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enemy is under troll mushroom effect. He cannot attack now..
        /// </summary>
        public static string EnemyIsUnderTrollMushroomEffect {
            get {
                return ResourceManager.GetString("EnemyIsUnderTrollMushroomEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Engraved Fangs.
        /// </summary>
        public static string EngravedFangs {
            get {
                return ResourceManager.GetString("EngravedFangs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reduce beasts armor by {0}%.
        /// </summary>
        public static string EngravedFangsDescription {
            get {
                return ResourceManager.GetString("EngravedFangsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Feathers Of Hope.
        /// </summary>
        public static string FeathersOfHope {
            get {
                return ResourceManager.GetString("FeathersOfHope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gain {0} HP on dodge.
        /// </summary>
        public static string FeathersOfHopeDescription {
            get {
                return ResourceManager.GetString("FeathersOfHopeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fidelity Card.
        /// </summary>
        public static string FidelityCard {
            get {
                return ResourceManager.GetString("FidelityCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}% discount with merchants.
        /// </summary>
        public static string FidelityCardDescription {
            get {
                return ResourceManager.GetString("FidelityCardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fight !.
        /// </summary>
        public static string Fight {
            get {
                return ResourceManager.GetString("Fight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hunter&apos;s Flute.
        /// </summary>
        public static string FluteOfHunter {
            get {
                return ResourceManager.GetString("FluteOfHunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reduce beasts strengh by {0}%.
        /// </summary>
        public static string FluteOfHunterDescription {
            get {
                return ResourceManager.GetString("FluteOfHunterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Found item: {0} – {1}.
        /// </summary>
        public static string FoundItem {
            get {
                return ResourceManager.GetString("FoundItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Game Over! Press Enter to exit..
        /// </summary>
        public static string GameOverPressEnterToExit {
            get {
                return ResourceManager.GetString("GameOverPressEnterToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Glasses of Clairvoyance.
        /// </summary>
        public static string GlassesOfClairvoyance {
            get {
                return ResourceManager.GetString("GlassesOfClairvoyance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your vision range cannot go below {0}.
        /// </summary>
        public static string GlassesOfClairvoyanceDescription {
            get {
                return ResourceManager.GetString("GlassesOfClairvoyanceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gold.
        /// </summary>
        public static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Goodbye..
        /// </summary>
        public static string Goodbye {
            get {
                return ResourceManager.GetString("Goodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Grol Mokbar&apos;s Ring.
        /// </summary>
        public static string GrolMokbarRing {
            get {
                return ResourceManager.GetString("GrolMokbarRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à +{0} enemies each wave.
        /// </summary>
        public static string GrolMokbarRingDescription {
            get {
                return ResourceManager.GetString("GrolMokbarRingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} has been destroyed!.
        /// </summary>
        public static string HasBeenDestroy {
            get {
                return ResourceManager.GetString("HasBeenDestroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hawk Eye.
        /// </summary>
        public static string HawkEye {
            get {
                return ResourceManager.GetString("HawkEye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}% chance of finding better bonus vision in chests.
        /// </summary>
        public static string HawkEyeDescription {
            get {
                return ResourceManager.GetString("HawkEyeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Healed {0} HP for {1} gold..
        /// </summary>
        public static string HealedHpForGold {
            get {
                return ResourceManager.GetString("HealedHpForGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à High Priest Prophet of Flesh.
        /// </summary>
        public static string HighPriest {
            get {
                return ResourceManager.GetString("HighPriest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Holy Bible.
        /// </summary>
        public static string HolyBible {
            get {
                return ResourceManager.GetString("HolyBible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reduce undead strengh by {0}%.
        /// </summary>
        public static string HolyBibleDescription {
            get {
                return ResourceManager.GetString("HolyBibleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HP.
        /// </summary>
        public static string HP {
            get {
                return ResourceManager.GetString("HP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inventory.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inventory full. Choose item to drop:.
        /// </summary>
        public static string InventoryFull {
            get {
                return ResourceManager.GetString("InventoryFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à is under attack.
        /// </summary>
        public static string IsUnderAttack {
            get {
                return ResourceManager.GetString("IsUnderAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Just talking.
        /// </summary>
        public static string JustTalking {
            get {
                return ResourceManager.GetString("JustTalking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keep current inventory.
        /// </summary>
        public static string KeepCurrentInventory {
            get {
                return ResourceManager.GetString("KeepCurrentInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Legless Zombie.
        /// </summary>
        public static string LeglessZombie {
            get {
                return ResourceManager.GetString("LeglessZombie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LifePoint.
        /// </summary>
        public static string LifePoint {
            get {
                return ResourceManager.GetString("LifePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lucky Millor&apos;s Left Hand.
        /// </summary>
        public static string LuckyMillorLeftHand {
            get {
                return ResourceManager.GetString("LuckyMillorLeftHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à +{0}% chance to find better bonuses.
        /// </summary>
        public static string LuckyMillorLeftHandDescription {
            get {
                return ResourceManager.GetString("LuckyMillorLeftHandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lvl..
        /// </summary>
        public static string Lvl {
            get {
                return ResourceManager.GetString("Lvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Max HP.
        /// </summary>
        public static string MaxHp {
            get {
                return ResourceManager.GetString("MaxHp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MaxLifePoint.
        /// </summary>
        public static string MaxLifePoint {
            get {
                return ResourceManager.GetString("MaxLifePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maybe later..
        /// </summary>
        public static string MaybeLater {
            get {
                return ResourceManager.GetString("MaybeLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mercenary.
        /// </summary>
        public static string Mercenary {
            get {
                return ResourceManager.GetString("Mercenary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move.
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I need healing..
        /// </summary>
        public static string NeedHealing {
            get {
                return ResourceManager.GetString("NeedHealing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Night.
        /// </summary>
        public static string Night {
            get {
                return ResourceManager.GetString("Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No camp to repair.
        /// </summary>
        public static string NoCampToRepair {
            get {
                return ResourceManager.GetString("NoCampToRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Watcher lantern of Nordheim.
        /// </summary>
        public static string NordheimWatcherLantern {
            get {
                return ResourceManager.GetString("NordheimWatcherLantern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reduce outlaws strengh by {0}%.
        /// </summary>
        public static string NordheimWatcherLanternDescription {
            get {
                return ResourceManager.GetString("NordheimWatcherLanternDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You do not have enough gold..
        /// </summary>
        public static string NotEnoughGold {
            get {
                return ResourceManager.GetString("NotEnoughGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is nothing to repair here..
        /// </summary>
        public static string NothingToRepair {
            get {
                return ResourceManager.GetString("NothingToRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Novice of the fresh meat cult.
        /// </summary>
        public static string Novice {
            get {
                return ResourceManager.GetString("Novice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Old Giant Wooden Club.
        /// </summary>
        public static string OldGiantWoodenClub {
            get {
                return ResourceManager.GetString("OldGiantWoodenClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Breaks {0} armor when less strength than opponent&apos;s armor.
        /// </summary>
        public static string OldGiantWoodenClubDescription {
            get {
                return ResourceManager.GetString("OldGiantWoodenClubDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paladin Necklace.
        /// </summary>
        public static string PaladinNecklace {
            get {
                return ResourceManager.GetString("PaladinNecklace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reduce enemies critical damage by {0}%.
        /// </summary>
        public static string PaladinNecklaceDescription {
            get {
                return ResourceManager.GetString("PaladinNecklaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pay and heal.
        /// </summary>
        public static string PayAndHeal {
            get {
                return ResourceManager.GetString("PayAndHeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pay and repair.
        /// </summary>
        public static string PayAndRepair {
            get {
                return ResourceManager.GetString("PayAndRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à picked.
        /// </summary>
        public static string Picked {
            get {
                return ResourceManager.GetString("Picked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pickpocket.
        /// </summary>
        public static string Pickpocket {
            get {
                return ResourceManager.GetString("Pickpocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plague Ghoul.
        /// </summary>
        public static string PlagueGhoul {
            get {
                return ResourceManager.GetString("PlagueGhoul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Player.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press any key to continue....
        /// </summary>
        public static string PressAnyKeyToContinue {
            get {
                return ResourceManager.GetString("PressAnyKeyToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scarlet Priest.
        /// </summary>
        public static string Priest {
            get {
                return ResourceManager.GetString("Priest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prospector&apos;s Key.
        /// </summary>
        public static string ProspectorKey {
            get {
                return ResourceManager.GetString("ProspectorKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à +{0} treasure chests at each wave.
        /// </summary>
        public static string ProspectorKeyDescription {
            get {
                return ResourceManager.GetString("ProspectorKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repaired camp for +{0} HP (cost {1} gold)..
        /// </summary>
        public static string RepairedCampForHpCost {
            get {
                return ResourceManager.GetString("RepairedCampForHpCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repair the camp..
        /// </summary>
        public static string RepairTheCamp {
            get {
                return ResourceManager.GetString("RepairTheCamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Revenant.
        /// </summary>
        public static string Revenant {
            get {
                return ResourceManager.GetString("Revenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rewards :.
        /// </summary>
        public static string Rewards {
            get {
                return ResourceManager.GetString("Rewards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ring Of Endurance.
        /// </summary>
        public static string RingOfEndurance {
            get {
                return ResourceManager.GetString("RingOfEndurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Grants +{0} HP at the start of each battle.
        /// </summary>
        public static string RingOfEnduranceDescription {
            get {
                return ResourceManager.GetString("RingOfEnduranceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Royal Guard Gauntlet.
        /// </summary>
        public static string RoyalGuardGauntlet {
            get {
                return ResourceManager.GetString("RoyalGuardGauntlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à +{0}% critical chance.
        /// </summary>
        public static string RoyalGuardGauntletDescription {
            get {
                return ResourceManager.GetString("RoyalGuardGauntletDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Royal Guard Shield.
        /// </summary>
        public static string RoyalGuardShield {
            get {
                return ResourceManager.GetString("RoyalGuardShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reduce enemies critical chance by {0}%.
        /// </summary>
        public static string RoyalGuardShieldDescription {
            get {
                return ResourceManager.GetString("RoyalGuardShieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sacred Crucifix.
        /// </summary>
        public static string SacredCrucifix {
            get {
                return ResourceManager.GetString("SacredCrucifix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reduce undead armor by {0}%.
        /// </summary>
        public static string SacredCrucifixDescription {
            get {
                return ResourceManager.GetString("SacredCrucifixDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauerkraut effigy.
        /// </summary>
        public static string SauerkrautEffigy {
            get {
                return ResourceManager.GetString("SauerkrautEffigy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reduce cultist armor by {0}%.
        /// </summary>
        public static string SauerkrautEffigyDescription {
            get {
                return ResourceManager.GetString("SauerkrautEffigyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Seal of Living Flesh.
        /// </summary>
        public static string SealOfLivingFlesh {
            get {
                return ResourceManager.GetString("SealOfLivingFlesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à +{0}HP on critical damage.
        /// </summary>
        public static string SealOfLivingFleshDescription {
            get {
                return ResourceManager.GetString("SealOfLivingFleshDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Seal Of Wisdom.
        /// </summary>
        public static string SealOfWisdom {
            get {
                return ResourceManager.GetString("SealOfWisdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à +{0}% more experience from battles.
        /// </summary>
        public static string SealOfWisdomDescription {
            get {
                return ResourceManager.GetString("SealOfWisdomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Champion’s Shield.
        /// </summary>
        public static string ShieldOfChampion {
            get {
                return ResourceManager.GetString("ShieldOfChampion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Provides +{0} armor against bosses..
        /// </summary>
        public static string ShieldOfChampionDescription {
            get {
                return ResourceManager.GetString("ShieldOfChampionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à shred {0} armor.
        /// </summary>
        public static string ShredArmor {
            get {
                return ResourceManager.GetString("ShredArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Skeleton.
        /// </summary>
        public static string Skeleton {
            get {
                return ResourceManager.GetString("Skeleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Speed.
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spider Nest.
        /// </summary>
        public static string SpiderNest {
            get {
                return ResourceManager.GetString("SpiderNest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à steal {0} HP.
        /// </summary>
        public static string StealHp {
            get {
                return ResourceManager.GetString("StealHp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Steps: {0} | Lvl: {1}.
        /// </summary>
        public static string StepAndLevel {
            get {
                return ResourceManager.GetString("StepAndLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Steps.
        /// </summary>
        public static string Steps {
            get {
                return ResourceManager.GetString("Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à StopWatch.
        /// </summary>
        public static string StopWatch {
            get {
                return ResourceManager.GetString("StopWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Don&apos;t count one step every {0} steps.
        /// </summary>
        public static string StopWatchDescription {
            get {
                return ResourceManager.GetString("StopWatchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Strength.
        /// </summary>
        public static string Strength {
            get {
                return ResourceManager.GetString("Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is under attack! HP:{1}/{2}.
        /// </summary>
        public static string StructureUnderAttack {
            get {
                return ResourceManager.GetString("StructureUnderAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sunrise.
        /// </summary>
        public static string Sunrise {
            get {
                return ResourceManager.GetString("Sunrise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sunset.
        /// </summary>
        public static string Sunset {
            get {
                return ResourceManager.GetString("Sunset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Talisman of peace.
        /// </summary>
        public static string TalismanOfPeace {
            get {
                return ResourceManager.GetString("TalismanOfPeace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -{0} enemies each wave.
        /// </summary>
        public static string TalismanOfPeaceDescription {
            get {
                return ResourceManager.GetString("TalismanOfPeaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Talisman Of The Last Breath‎.
        /// </summary>
        public static string TalismanOfTheLastBreath {
            get {
                return ResourceManager.GetString("TalismanOfTheLastBreath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Survive once per combat to fatal blow.
        /// </summary>
        public static string TalismanOfTheLastBreathDescription {
            get {
                return ResourceManager.GetString("TalismanOfTheLastBreathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The camp is already fully repaired..
        /// </summary>
        public static string TheCampIsAlreadyFullyRepair {
            get {
                return ResourceManager.GetString("TheCampIsAlreadyFullyRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Elder Lich.
        /// </summary>
        public static string TheElderLich {
            get {
                return ResourceManager.GetString("TheElderLich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The End! Press Enter to exit..
        /// </summary>
        public static string TheEndPressEnterToExit {
            get {
                return ResourceManager.GetString("TheEndPressEnterToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The enemy deals {0} damage to you.
        /// </summary>
        public static string TheEnemyDealDamageToYou {
            get {
                return ResourceManager.GetString("TheEnemyDealDamageToYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The enemy dodged your attack!.
        /// </summary>
        public static string TheEnemyDodgedYourAttack {
            get {
                return ResourceManager.GetString("TheEnemyDodgedYourAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The fog intensifies. New enemies and treasures have appeared!.
        /// </summary>
        public static string TheFogIntensifies {
            get {
                return ResourceManager.GetString("TheFogIntensifies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Juvenile Green Wyvern.
        /// </summary>
        public static string TheJuvenileGreenWyvern {
            get {
                return ResourceManager.GetString("TheJuvenileGreenWyvern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The night arrives.
        /// </summary>
        public static string TheNightArrives {
            get {
                return ResourceManager.GetString("TheNightArrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The sun rises.
        /// </summary>
        public static string TheSunRises {
            get {
                return ResourceManager.GetString("TheSunRises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The sun sets. Be aware of the night ....
        /// </summary>
        public static string TheSunSets {
            get {
                return ResourceManager.GetString("TheSunSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thorn Breastplate.
        /// </summary>
        public static string ThornBreastplate {
            get {
                return ResourceManager.GetString("ThornBreastplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 60% chances that enemies take {0} damage if they hit you.
        /// </summary>
        public static string ThornBreastplateDescription {
            get {
                return ResourceManager.GetString("ThornBreastplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Troll&apos;s Mushroom.
        /// </summary>
        public static string TrollMushroom {
            get {
                return ResourceManager.GetString("TrollMushroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attack every 2 turns, +{0}% damage.
        /// </summary>
        public static string TrollMushroomDescription {
            get {
                return ResourceManager.GetString("TrollMushroomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Upgraded {0} to value {1}.
        /// </summary>
        public static string UpgradedItemTo {
            get {
                return ResourceManager.GetString("UpgradedItemTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vision.
        /// </summary>
        public static string Vision {
            get {
                return ResourceManager.GetString("Vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Watchtower archer.
        /// </summary>
        public static string WatchtowerArcher {
            get {
                return ResourceManager.GetString("WatchtowerArcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Werewolf.
        /// </summary>
        public static string Werewolf {
            get {
                return ResourceManager.GetString("Werewolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What else can I do ?.
        /// </summary>
        public static string WhatElseCanIDo {
            get {
                return ResourceManager.GetString("WhatElseCanIDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Where are we ?.
        /// </summary>
        public static string WhereAreWe {
            get {
                return ResourceManager.GetString("WhereAreWe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wild Bear.
        /// </summary>
        public static string WildBear {
            get {
                return ResourceManager.GetString("WildBear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wild little bear.
        /// </summary>
        public static string WildLittleBear {
            get {
                return ResourceManager.GetString("WildLittleBear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wolf.
        /// </summary>
        public static string Wolf {
            get {
                return ResourceManager.GetString("Wolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XP.
        /// </summary>
        public static string XP {
            get {
                return ResourceManager.GetString("XP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assassin : Yann The Silent.
        /// </summary>
        public static string YannTheSilent {
            get {
                return ResourceManager.GetString("YannTheSilent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You already own {0}, not upgradable..
        /// </summary>
        public static string YouAlreadyOwnItemNotUpgradable {
            get {
                return ResourceManager.GetString("YouAlreadyOwnItemNotUpgradable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are under troll mushroom effect. You cannot attack now..
        /// </summary>
        public static string YouAreUnderTrollMushroomEffect {
            get {
                return ResourceManager.GetString("YouAreUnderTrollMushroomEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You deal {0} damage.
        /// </summary>
        public static string YouDealDamage {
            get {
                return ResourceManager.GetString("YouDealDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You defeated all bosses.
        /// </summary>
        public static string YouDefeatedAllBosses {
            get {
                return ResourceManager.GetString("YouDefeatedAllBosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You defeated all bosses. Now it&apos;s peaceful. Thanks for playing!.
        /// </summary>
        public static string YouDefeatedAllBossesThanksForPlaying {
            get {
                return ResourceManager.GetString("YouDefeatedAllBossesThanksForPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You died ....
        /// </summary>
        public static string YouDied {
            get {
                return ResourceManager.GetString("YouDied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You dodged the enemy&apos;s attack!.
        /// </summary>
        public static string YouDodgedTheEnemyAttack {
            get {
                return ResourceManager.GetString("YouDodgedTheEnemyAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You dodged the enemy&apos;s attack and gain {0} HP !.
        /// </summary>
        public static string YouDodgedTheEnemyAttackAndGainHp {
            get {
                return ResourceManager.GetString("YouDodgedTheEnemyAttackAndGainHp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You found a treasure! Choose your bonus:.
        /// </summary>
        public static string YouFoundATreasureChooseABonus {
            get {
                return ResourceManager.GetString("YouFoundATreasureChooseABonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You heal {0} HP with your ring of endurance..
        /// </summary>
        public static string YouHealWithYourRingOfEndurance {
            get {
                return ResourceManager.GetString("YouHealWithYourRingOfEndurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You leveled up to level {0} !.
        /// </summary>
        public static string YouLeveledUp {
            get {
                return ResourceManager.GetString("YouLeveledUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You survived a fatal blow with your talisman but it has run out for this combat..
        /// </summary>
        public static string YouSurvivedAFatalBlowWithYourTalisman {
            get {
                return ResourceManager.GetString("YouSurvivedAFatalBlowWithYourTalisman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You talked with {0}..
        /// </summary>
        public static string YouTalkedWith {
            get {
                return ResourceManager.GetString("YouTalkedWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You were attacked and you defeated your enemy !.
        /// </summary>
        public static string YouWereAttackedAndDefeatedYourEnemy {
            get {
                return ResourceManager.GetString("YouWereAttackedAndDefeatedYourEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You were killed by {0}..
        /// </summary>
        public static string YouWereKilledBy {
            get {
                return ResourceManager.GetString("YouWereKilledBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blood Zealot.
        /// </summary>
        public static string Zealot {
            get {
                return ResourceManager.GetString("Zealot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zombie.
        /// </summary>
        public static string Zombie {
            get {
                return ResourceManager.GetString("Zombie", resourceCulture);
            }
        }
    }
}
