namespace Roguelike.Core.Game.Collectables.Items;

public enum ItemId
{
    CapeOfInvisibility = 1,
    DaggerLifeSteal = 2,
    GlassesOfClairvoyance = 3,
    BootsOfEchoStep = 4,
    TalismanOfTheLastBreath = 5,
    ThornBreastplate = 6,
    FeathersOfHope = 7,
    RoyalGuardGauntlet = 8,
    RoyalGuardShield = 9,
    BerserkerNecklace = 10,
    PaladinNecklace = 11,
    HolyBible = 12,
    SacredCrucifix = 13,
    RingOfEndurance = 14,
    BladeOfHeroes = 15,
    ShieldOfChampion = 16,
    FluteOfHunter = 17,
    EngravedFangs = 18,
    EnchantedPouch = 19,
    SealOfWisdom = 20,
    ProspectorKey = 21,
    HawkEye = 22,
    FidelityCard = 23,
    TrollMushroom = 24,
    OldGiantWoodenClub = 25,
    LuckyMillorLeftHand = 26,
    GrolMokbarRing = 27,
    TalismanOfPeace = 28,
    SealOfLivingFlesh = 29,
    StopWatch = 30
}
