//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roguelike.Console.Properties.i18n {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Roguelike.Console.Properties.i18n.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A boss arrives.
        /// </summary>
        internal static string ABossArrives {
            get {
                return ResourceManager.GetString("ABossArrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Greetings, traveler. Welcome to Oneheim… or what remains of it. This village is but a heap of ruins. I have raised a camp here and set palisades against the night. Beware, for beyond these walls danger waits at every step..
        /// </summary>
        internal static string ArminFirstMeeting {
            get {
                return ResourceManager.GetString("ArminFirstMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back again? The wilds look harsh today. Tell me, friend, what may I do for you?.
        /// </summary>
        internal static string ArminMeeting {
            get {
                return ResourceManager.GetString("ArminMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To arms! The shadows breach our palisades! Hold fast! We shall not yield!.
        /// </summary>
        internal static string ArminMeetingBaseCampUnderAttack {
            get {
                return ResourceManager.GetString("ArminMeetingBaseCampUnderAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I heard ghastly cries beyond the walls, freezing the blood in my veins. Some foul creature prowls in the shadows. Beware, traveler..
        /// </summary>
        internal static string ArminMeetingFirstBossComing {
            get {
                return ResourceManager.GetString("ArminMeetingFirstBossComing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Word has spread, you have vanquished that dreadful beast. Never had I imagined such strength in you. It is a true blessing to have you among us! Accept my eternal gratitude. Tell me, how might I repay such a debt?.
        /// </summary>
        internal static string ArminMeetingFirstBossDefeated {
            get {
                return ResourceManager.GetString("ArminMeetingFirstBossDefeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travelers speak of a mighty foe haunting these lands. If only a valiant soul were strong enough to deliver us from this bane… May the camp’s palisades hold until then..
        /// </summary>
        internal static string ArminMeetingFirstBossHere {
            get {
                return ResourceManager.GetString("ArminMeetingFirstBossHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à By the gods, you look on the brink of collapse! Rest a while. This camp was meant as a haven for the weary..
        /// </summary>
        internal static string ArminMeetingPlayerLowLife {
            get {
                return ResourceManager.GetString("ArminMeetingPlayerLowLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à That is a heavy purse you carry. May it serve to raise Oneheim anew and kindle fresh hopes..
        /// </summary>
        internal static string ArminMeetingPlayerRich {
            get {
                return ResourceManager.GetString("ArminMeetingPlayerRich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Base Camp HP: .
        /// </summary>
        internal static string BaseCampHp {
            get {
                return ResourceManager.GetString("BaseCampHp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Be carefull, you are not safe here ....
        /// </summary>
        internal static string BeCarefullYouAreNotSafeHere {
            get {
                return ResourceManager.GetString("BeCarefullYouAreNotSafeHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The camp is already in perfect shape..
        /// </summary>
        internal static string CampAlreadyRepair {
            get {
                return ResourceManager.GetString("CampAlreadyRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can you heal me?.
        /// </summary>
        internal static string CanYouHealMe {
            get {
                return ResourceManager.GetString("CanYouHealMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can you repair the camp?.
        /// </summary>
        internal static string CanYouRepairTheCamp {
            get {
                return ResourceManager.GetString("CanYouRepairTheCamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Game Over! Press Enter to exit..
        /// </summary>
        internal static string GameOverPressEnterToExit {
            get {
                return ResourceManager.GetString("GameOverPressEnterToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Goodbye..
        /// </summary>
        internal static string Goodbye {
            get {
                return ResourceManager.GetString("Goodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maybe later..
        /// </summary>
        internal static string MaybeLater {
            get {
                return ResourceManager.GetString("MaybeLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I need healing..
        /// </summary>
        internal static string NeedHealing {
            get {
                return ResourceManager.GetString("NeedHealing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No camp to repair.
        /// </summary>
        internal static string NoCampToRepair {
            get {
                return ResourceManager.GetString("NoCampToRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You do not have enough gold..
        /// </summary>
        internal static string NotEnoughGold {
            get {
                return ResourceManager.GetString("NotEnoughGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is nothing to repair here..
        /// </summary>
        internal static string NothingToRepair {
            get {
                return ResourceManager.GetString("NothingToRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pay and repair.
        /// </summary>
        internal static string PayAndRepair {
            get {
                return ResourceManager.GetString("PayAndRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repair the camp..
        /// </summary>
        internal static string RepairTheCamp {
            get {
                return ResourceManager.GetString("RepairTheCamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Steps: {0} | Lvl: {1}.
        /// </summary>
        internal static string StepAndLevel {
            get {
                return ResourceManager.GetString("StepAndLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The camp is already fully repaired..
        /// </summary>
        internal static string TheCampIsAlreadyFullyRepair {
            get {
                return ResourceManager.GetString("TheCampIsAlreadyFullyRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The End! Press Enter to exit..
        /// </summary>
        internal static string TheEndPressEnterToExit {
            get {
                return ResourceManager.GetString("TheEndPressEnterToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The enemy dodged your attack!.
        /// </summary>
        internal static string TheEnemyDodgedYourAttack {
            get {
                return ResourceManager.GetString("TheEnemyDodgedYourAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The fog intensifies. New enemies and treasures have appeared!.
        /// </summary>
        internal static string TheFogIntensifies {
            get {
                return ResourceManager.GetString("TheFogIntensifies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You defeated all bosses.
        /// </summary>
        internal static string YouDefeatedAllBosses {
            get {
                return ResourceManager.GetString("YouDefeatedAllBosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You dodged the enemy&apos;s attack!.
        /// </summary>
        internal static string YouDodgedTheEnemyAttack {
            get {
                return ResourceManager.GetString("YouDodgedTheEnemyAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You were attacked and you defeated your enemy !.
        /// </summary>
        internal static string YouWereAttackedAndDefeatedYourEnemy {
            get {
                return ResourceManager.GetString("YouWereAttackedAndDefeatedYourEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You were killed by {0}..
        /// </summary>
        internal static string YouWereKilledBy {
            get {
                return ResourceManager.GetString("YouWereKilledBy", resourceCulture);
            }
        }
    }
}
