//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roguelike.Console.Properties.i18n {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Roguelike.Console.Properties.i18n.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A boss arrives.
        /// </summary>
        internal static string ABossArrives {
            get {
                return ResourceManager.GetString("ABossArrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alpha Wolf.
        /// </summary>
        internal static string AlphaWolf {
            get {
                return ResourceManager.GetString("AlphaWolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are already full life.
        /// </summary>
        internal static string AlreadyFullHealth {
            get {
                return ResourceManager.GetString("AlreadyFullHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à and.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à and takes {0} thorns damage.
        /// </summary>
        internal static string AndTakeThornsDamage {
            get {
                return ResourceManager.GetString("AndTakeThornsDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Greetings, traveler. Welcome to Oneheim… or what remains of it. This village is but a heap of ruins. I have raised a camp here and set palisades against the night. Beware, for beyond these walls danger waits at every step..
        /// </summary>
        internal static string ArminFirstMeeting {
            get {
                return ResourceManager.GetString("ArminFirstMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I can patch you up for {0} gold. You will recover up to +{1} HP..
        /// </summary>
        internal static string ArminHealPitch {
            get {
                return ResourceManager.GetString("ArminHealPitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back again? The wilds look harsh today. Tell me, friend, what may I do for you?.
        /// </summary>
        internal static string ArminMeeting {
            get {
                return ResourceManager.GetString("ArminMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To arms! The shadows breach our palisades! Hold fast! We shall not yield!.
        /// </summary>
        internal static string ArminMeetingBaseCampUnderAttack {
            get {
                return ResourceManager.GetString("ArminMeetingBaseCampUnderAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I heard ghastly cries beyond the walls, freezing the blood in my veins. Some foul creature prowls in the shadows. Beware, traveler..
        /// </summary>
        internal static string ArminMeetingFirstBossComing {
            get {
                return ResourceManager.GetString("ArminMeetingFirstBossComing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Word has spread, you have vanquished that dreadful beast. Never had I imagined such strength in you. It is a true blessing to have you among us! Accept my eternal gratitude. Tell me, how might I repay such a debt?.
        /// </summary>
        internal static string ArminMeetingFirstBossDefeated {
            get {
                return ResourceManager.GetString("ArminMeetingFirstBossDefeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travelers speak of a mighty foe haunting these lands. If only a valiant soul were strong enough to deliver us from this bane… May the camp’s palisades hold until then..
        /// </summary>
        internal static string ArminMeetingFirstBossHere {
            get {
                return ResourceManager.GetString("ArminMeetingFirstBossHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à By the gods, you look on the brink of collapse! Rest a while. This camp was meant as a haven for the weary..
        /// </summary>
        internal static string ArminMeetingPlayerLowLife {
            get {
                return ResourceManager.GetString("ArminMeetingPlayerLowLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à That is a heavy purse you carry. May it serve to raise Oneheim anew and kindle fresh hopes..
        /// </summary>
        internal static string ArminMeetingPlayerRich {
            get {
                return ResourceManager.GetString("ArminMeetingPlayerRich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I can repair the camp for {0} gold (+{1} HP)..
        /// </summary>
        internal static string ArminRepairPitch {
            get {
                return ResourceManager.GetString("ArminRepairPitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Armor.
        /// </summary>
        internal static string Armor {
            get {
                return ResourceManager.GetString("Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Armored Zombie.
        /// </summary>
        internal static string ArmoredZombie {
            get {
                return ResourceManager.GetString("ArmoredZombie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Base Camp.
        /// </summary>
        internal static string BaseCamp {
            get {
                return ResourceManager.GetString("BaseCamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Base Camp HP: .
        /// </summary>
        internal static string BaseCampHp {
            get {
                return ResourceManager.GetString("BaseCampHp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Be carefull, you are not safe here ....
        /// </summary>
        internal static string BeCarefullYouAreNotSafeHere {
            get {
                return ResourceManager.GetString("BeCarefullYouAreNotSafeHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Berserker Necklace.
        /// </summary>
        internal static string BerserkerNecklace {
            get {
                return ResourceManager.GetString("BerserkerNecklace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à +{0}% critical damage.
        /// </summary>
        internal static string BerserkerNecklaceDescription {
            get {
                return ResourceManager.GetString("BerserkerNecklaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blade Of Heroes.
        /// </summary>
        internal static string BladeOfHeroes {
            get {
                return ResourceManager.GetString("BladeOfHeroes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deals +{0} strengh against bosses.
        /// </summary>
        internal static string BladeOfHeroesDescription {
            get {
                return ResourceManager.GetString("BladeOfHeroesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Boots of Echo Step.
        /// </summary>
        internal static string BootsOfEchoStep {
            get {
                return ResourceManager.GetString("BootsOfEchoStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dodge increased by {0}% if your faster than you opponent.
        /// </summary>
        internal static string BootsOfEchoStepDescription {
            get {
                return ResourceManager.GetString("BootsOfEchoStepDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The camp is already in perfect shape..
        /// </summary>
        internal static string CampAlreadyRepair {
            get {
                return ResourceManager.GetString("CampAlreadyRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can you heal me?.
        /// </summary>
        internal static string CanYouHealMe {
            get {
                return ResourceManager.GetString("CanYouHealMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can you repair the camp?.
        /// </summary>
        internal static string CanYouRepairTheCamp {
            get {
                return ResourceManager.GetString("CanYouRepairTheCamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cape Of Invisibility.
        /// </summary>
        internal static string CapeOfInvisibility {
            get {
                return ResourceManager.GetString("CapeOfInvisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decrease by {0} enemies vision range.
        /// </summary>
        internal static string CapeOfInvisibilityDescription {
            get {
                return ResourceManager.GetString("CapeOfInvisibilityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choices.
        /// </summary>
        internal static string Choices {
            get {
                return ResourceManager.GetString("Choices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Combat occurred!.
        /// </summary>
        internal static string CombatOccurred {
            get {
                return ResourceManager.GetString("CombatOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dagger of life steal.
        /// </summary>
        internal static string DaggerOfLifeSteal {
            get {
                return ResourceManager.GetString("DaggerOfLifeSteal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 60% chances to steal up to {0} life points from the enemy on hit..
        /// </summary>
        internal static string DaggerOfLifeStealDescription {
            get {
                return ResourceManager.GetString("DaggerOfLifeStealDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dropped.
        /// </summary>
        internal static string Dropped {
            get {
                return ResourceManager.GetString("Dropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enchanted Pouch.
        /// </summary>
        internal static string EnchantedPouch {
            get {
                return ResourceManager.GetString("EnchantedPouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à +{0}% more gold after each victory.
        /// </summary>
        internal static string EnchantedPouchDescription {
            get {
                return ResourceManager.GetString("EnchantedPouchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enemy defeated!.
        /// </summary>
        internal static string EnemyDefeated {
            get {
                return ResourceManager.GetString("EnemyDefeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Engraved Fangs.
        /// </summary>
        internal static string EngravedFangs {
            get {
                return ResourceManager.GetString("EngravedFangs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reduces by {0} the ARMOR of beasts.
        /// </summary>
        internal static string EngravedFangsDescription {
            get {
                return ResourceManager.GetString("EngravedFangsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Feathers Of Hope.
        /// </summary>
        internal static string FeathersOfHope {
            get {
                return ResourceManager.GetString("FeathersOfHope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gain {0}% HP on dodge.
        /// </summary>
        internal static string FeathersOfHopeDescription {
            get {
                return ResourceManager.GetString("FeathersOfHopeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fidelity Card.
        /// </summary>
        internal static string FidelityCard {
            get {
                return ResourceManager.GetString("FidelityCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}% discount with merchants.
        /// </summary>
        internal static string FidelityCardDescription {
            get {
                return ResourceManager.GetString("FidelityCardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fight !.
        /// </summary>
        internal static string Fight {
            get {
                return ResourceManager.GetString("Fight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hunter&apos;s Flute.
        /// </summary>
        internal static string FluteOfHunter {
            get {
                return ResourceManager.GetString("FluteOfHunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decreases by {0} the ATK of beasts.
        /// </summary>
        internal static string FluteOfHunterDescription {
            get {
                return ResourceManager.GetString("FluteOfHunterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Found item: {0} – {1}.
        /// </summary>
        internal static string FoundItem {
            get {
                return ResourceManager.GetString("FoundItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Game Over! Press Enter to exit..
        /// </summary>
        internal static string GameOverPressEnterToExit {
            get {
                return ResourceManager.GetString("GameOverPressEnterToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Glasses of Clairvoyance.
        /// </summary>
        internal static string GlassesOfClairvoyance {
            get {
                return ResourceManager.GetString("GlassesOfClairvoyance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your vision range cannot go below {0}.
        /// </summary>
        internal static string GlassesOfClairvoyanceDescription {
            get {
                return ResourceManager.GetString("GlassesOfClairvoyanceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gold.
        /// </summary>
        internal static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Goodbye..
        /// </summary>
        internal static string Goodbye {
            get {
                return ResourceManager.GetString("Goodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} has been destroyed!.
        /// </summary>
        internal static string HasBeenDestroy {
            get {
                return ResourceManager.GetString("HasBeenDestroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hawk Eye.
        /// </summary>
        internal static string HawkEye {
            get {
                return ResourceManager.GetString("HawkEye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}% chance of finding better bonus vision in chests.
        /// </summary>
        internal static string HawkEyeDescription {
            get {
                return ResourceManager.GetString("HawkEyeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Healed {0} HP for {1} gold..
        /// </summary>
        internal static string HealedHpForGold {
            get {
                return ResourceManager.GetString("HealedHpForGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Holy Bible.
        /// </summary>
        internal static string HolyBible {
            get {
                return ResourceManager.GetString("HolyBible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reduce undead strengh by {0}.
        /// </summary>
        internal static string HolyBibleDescription {
            get {
                return ResourceManager.GetString("HolyBibleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à HP.
        /// </summary>
        internal static string HP {
            get {
                return ResourceManager.GetString("HP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inventory.
        /// </summary>
        internal static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inventory full. Choose item to drop:.
        /// </summary>
        internal static string InventoryFull {
            get {
                return ResourceManager.GetString("InventoryFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keep current inventory.
        /// </summary>
        internal static string KeepCurrentInventory {
            get {
                return ResourceManager.GetString("KeepCurrentInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Legless Zombie.
        /// </summary>
        internal static string LeglessZombie {
            get {
                return ResourceManager.GetString("LeglessZombie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LifePoint.
        /// </summary>
        internal static string LifePoint {
            get {
                return ResourceManager.GetString("LifePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Max HP.
        /// </summary>
        internal static string MaxHp {
            get {
                return ResourceManager.GetString("MaxHp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MaxLifePoint.
        /// </summary>
        internal static string MaxLifePoint {
            get {
                return ResourceManager.GetString("MaxLifePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maybe later..
        /// </summary>
        internal static string MaybeLater {
            get {
                return ResourceManager.GetString("MaybeLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move.
        /// </summary>
        internal static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I need healing..
        /// </summary>
        internal static string NeedHealing {
            get {
                return ResourceManager.GetString("NeedHealing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No camp to repair.
        /// </summary>
        internal static string NoCampToRepair {
            get {
                return ResourceManager.GetString("NoCampToRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You do not have enough gold..
        /// </summary>
        internal static string NotEnoughGold {
            get {
                return ResourceManager.GetString("NotEnoughGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is nothing to repair here..
        /// </summary>
        internal static string NothingToRepair {
            get {
                return ResourceManager.GetString("NothingToRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paladin Necklace.
        /// </summary>
        internal static string PaladinNecklace {
            get {
                return ResourceManager.GetString("PaladinNecklace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reduce enemies critical damage by {0}%.
        /// </summary>
        internal static string PaladinNecklaceDescription {
            get {
                return ResourceManager.GetString("PaladinNecklaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pay and heal.
        /// </summary>
        internal static string PayAndHeal {
            get {
                return ResourceManager.GetString("PayAndHeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pay and repair.
        /// </summary>
        internal static string PayAndRepair {
            get {
                return ResourceManager.GetString("PayAndRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à picked.
        /// </summary>
        internal static string Picked {
            get {
                return ResourceManager.GetString("Picked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plague Ghoul.
        /// </summary>
        internal static string PlagueGhoul {
            get {
                return ResourceManager.GetString("PlagueGhoul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press any key to continue....
        /// </summary>
        internal static string PressAnyKeyToContinue {
            get {
                return ResourceManager.GetString("PressAnyKeyToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prospector&apos;s Key.
        /// </summary>
        internal static string ProspectorKey {
            get {
                return ResourceManager.GetString("ProspectorKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à +{0} treasure chests at each wave.
        /// </summary>
        internal static string ProspectorKeyDescription {
            get {
                return ResourceManager.GetString("ProspectorKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quit.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repaired camp for +{0} HP (cost {1} gold)..
        /// </summary>
        internal static string RepairedCampForHpCost {
            get {
                return ResourceManager.GetString("RepairedCampForHpCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repair the camp..
        /// </summary>
        internal static string RepairTheCamp {
            get {
                return ResourceManager.GetString("RepairTheCamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Revenant.
        /// </summary>
        internal static string Revenant {
            get {
                return ResourceManager.GetString("Revenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rewards :.
        /// </summary>
        internal static string Rewards {
            get {
                return ResourceManager.GetString("Rewards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ring Of Endurance.
        /// </summary>
        internal static string RingOfEndurance {
            get {
                return ResourceManager.GetString("RingOfEndurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Grants +{0} HP at the start of each battle.
        /// </summary>
        internal static string RingOfEnduranceDescription {
            get {
                return ResourceManager.GetString("RingOfEnduranceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Royal Guard Gauntlet.
        /// </summary>
        internal static string RoyalGuardGauntlet {
            get {
                return ResourceManager.GetString("RoyalGuardGauntlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à +{0}% critical chance.
        /// </summary>
        internal static string RoyalGuardGauntletDescription {
            get {
                return ResourceManager.GetString("RoyalGuardGauntletDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Royal Guard Shield.
        /// </summary>
        internal static string RoyalGuardShield {
            get {
                return ResourceManager.GetString("RoyalGuardShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reduce enemies critical chance by {0}%.
        /// </summary>
        internal static string RoyalGuardShieldDescription {
            get {
                return ResourceManager.GetString("RoyalGuardShieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sacred Crucifix.
        /// </summary>
        internal static string SacredCrucifix {
            get {
                return ResourceManager.GetString("SacredCrucifix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reduce undead armor by {0}.
        /// </summary>
        internal static string SacredCrucifixDescription {
            get {
                return ResourceManager.GetString("SacredCrucifixDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Seal Of Wisdom.
        /// </summary>
        internal static string SealOfWisdom {
            get {
                return ResourceManager.GetString("SealOfWisdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à +{0}% more experience from battles.
        /// </summary>
        internal static string SealOfWisdomDescription {
            get {
                return ResourceManager.GetString("SealOfWisdomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Champion’s Shield.
        /// </summary>
        internal static string ShieldOfChampion {
            get {
                return ResourceManager.GetString("ShieldOfChampion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Provides +{0} armor against bosses..
        /// </summary>
        internal static string ShieldOfChampionDescription {
            get {
                return ResourceManager.GetString("ShieldOfChampionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à shred {0} armor.
        /// </summary>
        internal static string ShredArmor {
            get {
                return ResourceManager.GetString("ShredArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Speed.
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spider Nest.
        /// </summary>
        internal static string SpiderNest {
            get {
                return ResourceManager.GetString("SpiderNest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à steal {0} HP.
        /// </summary>
        internal static string StealHp {
            get {
                return ResourceManager.GetString("StealHp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Steps: {0} | Lvl: {1}.
        /// </summary>
        internal static string StepAndLevel {
            get {
                return ResourceManager.GetString("StepAndLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Strength.
        /// </summary>
        internal static string Strength {
            get {
                return ResourceManager.GetString("Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is under attack! HP:{1}/{2}.
        /// </summary>
        internal static string StructureUnderAttack {
            get {
                return ResourceManager.GetString("StructureUnderAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Talisman Of The Last Breath‎.
        /// </summary>
        internal static string TalismanOfTheLastBreath {
            get {
                return ResourceManager.GetString("TalismanOfTheLastBreath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Survive only once to fatal blow.
        /// </summary>
        internal static string TalismanOfTheLastBreathDescription {
            get {
                return ResourceManager.GetString("TalismanOfTheLastBreathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The camp is already fully repaired..
        /// </summary>
        internal static string TheCampIsAlreadyFullyRepair {
            get {
                return ResourceManager.GetString("TheCampIsAlreadyFullyRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Elder Lich.
        /// </summary>
        internal static string TheElderLich {
            get {
                return ResourceManager.GetString("TheElderLich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The End! Press Enter to exit..
        /// </summary>
        internal static string TheEndPressEnterToExit {
            get {
                return ResourceManager.GetString("TheEndPressEnterToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The enemy deals {0} damage to you.
        /// </summary>
        internal static string TheEnemyDealDamageToYou {
            get {
                return ResourceManager.GetString("TheEnemyDealDamageToYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The enemy dodged your attack!.
        /// </summary>
        internal static string TheEnemyDodgedYourAttack {
            get {
                return ResourceManager.GetString("TheEnemyDodgedYourAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The fog intensifies. New enemies and treasures have appeared!.
        /// </summary>
        internal static string TheFogIntensifies {
            get {
                return ResourceManager.GetString("TheFogIntensifies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Juvenile Green Wyvern.
        /// </summary>
        internal static string TheJuvenileGreenWyvern {
            get {
                return ResourceManager.GetString("TheJuvenileGreenWyvern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thorn Breastplate.
        /// </summary>
        internal static string ThornBreastplate {
            get {
                return ResourceManager.GetString("ThornBreastplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 60% chances that enemies take {0} damage if they hit you.
        /// </summary>
        internal static string ThornBreastplateDescription {
            get {
                return ResourceManager.GetString("ThornBreastplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Upgraded {0} to value {1}.
        /// </summary>
        internal static string UpgradedItemTo {
            get {
                return ResourceManager.GetString("UpgradedItemTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vision.
        /// </summary>
        internal static string Vision {
            get {
                return ResourceManager.GetString("Vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Werewolf.
        /// </summary>
        internal static string Werewolf {
            get {
                return ResourceManager.GetString("Werewolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wild Bear.
        /// </summary>
        internal static string WildBear {
            get {
                return ResourceManager.GetString("WildBear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wolf.
        /// </summary>
        internal static string Wolf {
            get {
                return ResourceManager.GetString("Wolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XP.
        /// </summary>
        internal static string XP {
            get {
                return ResourceManager.GetString("XP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You already own {0}, not upgradable..
        /// </summary>
        internal static string YouAlreadyOwnItemNotUpgradable {
            get {
                return ResourceManager.GetString("YouAlreadyOwnItemNotUpgradable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You deal {0} damage.
        /// </summary>
        internal static string YouDealDamage {
            get {
                return ResourceManager.GetString("YouDealDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You defeated all bosses.
        /// </summary>
        internal static string YouDefeatedAllBosses {
            get {
                return ResourceManager.GetString("YouDefeatedAllBosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You defeated all bosses. Now it&apos;s peaceful. Thanks for playing!.
        /// </summary>
        internal static string YouDefeatedAllBossesThanksForPlaying {
            get {
                return ResourceManager.GetString("YouDefeatedAllBossesThanksForPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You died ....
        /// </summary>
        internal static string YouDied {
            get {
                return ResourceManager.GetString("YouDied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You dodged the enemy&apos;s attack!.
        /// </summary>
        internal static string YouDodgedTheEnemyAttack {
            get {
                return ResourceManager.GetString("YouDodgedTheEnemyAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You dodged the enemy&apos;s attack and gain {0} HP !.
        /// </summary>
        internal static string YouDodgedTheEnemyAttackAndGainHp {
            get {
                return ResourceManager.GetString("YouDodgedTheEnemyAttackAndGainHp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You found a treasure! Choose your bonus:.
        /// </summary>
        internal static string YouFoundATreasureChooseABonus {
            get {
                return ResourceManager.GetString("YouFoundATreasureChooseABonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You heal {0} HP with your ring of endurance..
        /// </summary>
        internal static string YouHealWithYourRingOfEndurance {
            get {
                return ResourceManager.GetString("YouHealWithYourRingOfEndurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You leveled up to level {0} !.
        /// </summary>
        internal static string YouLeveledUp {
            get {
                return ResourceManager.GetString("YouLeveledUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You survived a fatal blow with your talisman but it has been destroyed..
        /// </summary>
        internal static string YouSurvivedAFatalBlowWithYourTalisman {
            get {
                return ResourceManager.GetString("YouSurvivedAFatalBlowWithYourTalisman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You talked with {0}..
        /// </summary>
        internal static string YouTalkedWith {
            get {
                return ResourceManager.GetString("YouTalkedWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You were attacked and you defeated your enemy !.
        /// </summary>
        internal static string YouWereAttackedAndDefeatedYourEnemy {
            get {
                return ResourceManager.GetString("YouWereAttackedAndDefeatedYourEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You were killed by {0}..
        /// </summary>
        internal static string YouWereKilledBy {
            get {
                return ResourceManager.GetString("YouWereKilledBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zombie.
        /// </summary>
        internal static string Zombie {
            get {
                return ResourceManager.GetString("Zombie", resourceCulture);
            }
        }
    }
}
